pull: yes
mount_root: /var/docker_volumes
mount_state: directory

network_name: dockernet_gitea
network_state: present

container_state: started
container_restart: unless-stopped

database: gitea
database_user: gitea
database_password: gitea

port_http: "3000"
port_ssh: "3022"
