#!/bin/bash

function clean {
  rm -rf /arch-server/w /arch-server/arch-server-latest-x86_64.iso
  echo '' > ./arch/airootfs/etc/pacman.d/mirrorlist
  mkdir -p /arch-server/w /arch-server/build
}

function mirrors {
  curl -s "https://archlinux.org/mirrorlist/?country=US&protocol=https&use_mirror_status=on" \
    | sed -e 's/^#Server/Server/' -e '/^#/d' \
    | rankmirrors -n 5 - \
    > ./arch/airootfs/etc/pacman.d/mirrorlist
}

function build {
  clean
  mirrors
  mkarchiso -v -w /arch-server/w -o /arch-server ./arch
}

function release {
  if [ "$(git status --porcelain)" ]; then 
    echo "release needs a clean git"
    exit 1
  fi

  version="$(git describe --tags)"
  cp "/arch-server/arch-server-latest-x86_64.iso" "/arch-server/build/arch-server-${version}-x86_64.iso"
  ln -sf "/arch-server/build/arch-server-${version}-x86_64.iso" "/arch-server/build/arch-server-latest-x86_64.iso"
}

case $1 in
  clean) clean;;
  mirrors) mirrors;;
  build) build;;
  release) release;;
  *) build
esac