#!/bin/bash

function clean {
  rm -rf /tmp/w /arch-server/arch-server-latest-x86_64.iso
  echo '' > ./arch/airootfs/etc/pacman.d/mirrorlist
  mkdir -p /tmp/w /arch-server/build
}

function build {
  mkarchiso -v -w /tmp/w -o /arch-server ./arch
}

function release {
  build

  version="$(git describe --tags)"
  cp "/arch-server/arch-server-latest-x86_64.iso" "/arch-server/build/arch-server-${version}-x86_64.iso"
  ln -sf "/arch-server/build/arch-server-${version}-x86_64.iso" "/arch-server/build/arch-server-latest-x86_64.iso"

  echo "iso written to arch-server-${version}-x86_64.iso"
}

case $1 in
  clean) clean;;
  mirrors) mirrors;;
  build) build;;
  release) release;;
  *) build
esac