---
- name: ensure ia-download target
  become: yes
  tags:
    - data-getter
    - storage
  loop:
    - 3DS
    - WII
  ansible.builtin.file:
    owner: zero
    path: /storage/roms/{{ item }}
    state: directory

- name: ia-download to 3DS
  run_once: true
  loop:
    - nintendo-3ds-complete-collection
    - nintendo-3ds-complete-collection-pt2
  tags:
    - ia-download
    - docker-worker
  community.docker.docker_container:
    name: ia-download-{{ item }}
    image: gastrodon/ia-download
    command: "{{ item }}"
    pull: yes
    restart_policy: on-failure
    state: "{{ ia_download_state | default('started') }}"
    volumes:
      - /storage/roms/3DS:/ia

- name: ia-download to WII
  run_once: true
  loop:
    - wiiusaredump
    - wiiusaredump2
    - wiiusaredump3
  tags:
    - ia-download
    - required-docker
    - required-storage
    - docker-worker
  community.docker.docker_container:
    name: ia-download-{{ item }}
    image: gastrodon/ia-download
    command: "{{ item }}"
    pull: yes
    restart_policy: on-failure
    state: "{{ ia_download_state | default('started') }}"
    volumes:
      - /storage/roms/WII:/ia
