---
- name: ensure ia-download mount item
  loop: "{{ targets }}"
  become: yes
  file:
    owner: root
    path: "{{ mount.root }}/{{ item.1 }}"
    state: "{{ mount.state }}"

- name: ia-download target
  run_once: true
  loop: "{{ targets }}"
  docker_container:
    name: ia-download-{{ item.0 }}
    image: gastrodon/ia-download:latest
    pull: "{{ container.pull}}"
    command: "{{ item.0 }}"
    restart_policy: "{{ container.restart }}"
    state: "{{ container.state }}"
    volumes:
      - "{{ mount.root }}/{{ item.1 }}:/ia"
