---
- name: ensure nginx mount targets
  become: yes
  file:
    owner: root
    path: "{{ mount_root }}/nginx"
    state: "{{ mount_state }}"

- name: ensure nginx files populated
  become: yes
  loop:
    - nginx
    - ssl
  copy:
    owner: root
    src: "files/{{ item }}"
    dest: "{{ mount_root }}/nginx"

- name: ensure nginx container up
  docker_container:
    name: nginx
    image: nginx:stable-alpine
    pull: "{{ pull }}"
    restart: yes
    restart_policy: "{{ container_restart }}"
    networks:
      - name: "{{ router_network }}"
    volumes:
      - "{{ mount_root }}/nginx/nginx:/etc/nginx"
      - "{{ mount_root }}/nginx/ssl:/etc/ssl"
    ports:
      - "{{ port_http }}:80"
      - "{{ port_https }}:443"
