---
- name: ensure nginx mount targets
  become: yes
  file:
    owner: root
    path: "{{ mount.root }}/nginx"
    state: "{{ mount.state }}"

- name: ensure nginx files populated
  become: yes
  loop:
    - nginx
    - ssl
  copy:
    owner: root
    src: "files/{{ item }}"
    dest: "{{ mount.root }}/nginx"

- name: ensure nginx container up
  docker_container:
    name: nginx
    image: nginx:stable-alpine
    pull: "{{ container.pull }}"
    restart: yes
    restart_policy: "{{ container.restart }}"
    networks:
      - name: "{{ router_network }}"
    volumes:
      - "{{ mount.root }}/nginx/nginx:/etc/nginx"
      - "{{ mount.root }}/nginx/ssl:/etc/ssl"
    ports:
      - "{{ container.port.http }}:80"
      - "{{ container.port.https }}:443"
