---
- name: ensure ia-downloader on roms
  hosts: all
  vars:
    container_state: stopped
    check_mount: no
    targets:
      - [ wiiusaredump, WII ]
      - [ wiiusaredump2, WII ]
      - [ wiiusaredump3, WII ]
      - [ nintendo-3ds-complete-collection, 3DS ]
      - [ nintendo-3ds-complete-collection-pt2, 3DS ]
  roles:
    - pacman/nfs
    - ia-download
