---
- name: ensure qbittorrent mount
  become: yes
  loop:
    - downloads
    - config
  file:
    owner: root
    path: "{{ mount.root}}/qbittorrent/{{ item }}"
    state: "{{ mount.state }}"

- name: ensure qbittorrent container up
  docker_container:
    name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    pull: "{{ container.pull }}"
    restart_policy: "{{ container.restart }}"
    env:
      PUID: "1000"
      PGID: "1000"
      WEBUI_PORT: "{{ container.port.http }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ router_network }}"
        aliases:
          - qbittorrent
    volumes:
      - "{{ mount.root }}/qbittorrent/downloads:/downloads"
      - "{{ mount.root }}/qbittorrent/config:/config"
    expose:
      - "{{ container.port.http }}"
