---
- name: ensure qbittorrent mount
  become: yes
  loop:
    - downloads
    - config
  file:
    owner: root
    path: "{{ mount_root}}/qbittorrent/{{ item }}"
    state: "{{ mount_state }}"

- name: ensure qbittorrent container up
  docker_container:
    name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    pull: "{{ pull }}"
    restart_policy: "{{ container_restart }}"
    env:
      PUID: "1000"
      PGID: "1000"
      WEBUI_PORT: "{{ port_http }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ router_network }}"
        aliases:
          - qbittorrent
    volumes:
      - "{{ mount_root }}/qbittorrent/downloads:/downloads"
      - "{{ mount_root }}/qbittorrent/config:/config"
    expose:
      - "{{ port_http }}"
