---
- name: ensure global pip packages
  hosts: all

  tasks:
    - name: ensure python installed
      become: yes
      community.general.pacman:
        name:
          - python
          - python-pip
          - python-setuptools

    - name: ensure pip docker
      pip:
        name: docker
        state: latest
        extra_args: --user
