---
  - name: ensure python installed
    become: yes
    tags:
      - required-pip
      - required-docker
    community.general.pacman:
      name:
        - python
        - python-pip
        - python-setuptools

  - name: ensure pip docker
    tags:
      - required-docker
    pip:
      name: docker
      state: latest
      extra_args: --user
